# Big Query Specific Configs
# https://docs.getdbt.com/reference/resource-configs/bigquery-configs

name: 'elastic_dbt'
version: '1.0.0'
config-version: 2
profile: 'dbt'

# =====
# Paths
# =====

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]
clean-targets: ["target", "dbt_packages", "logs"]

# ======
# Models (https://docs.getdbt.com/reference/model-configs)
# ======

models:
  elastic_dbt:
    tmp:
      +materialized: view
    stg:
      +materialized: view
    warehouse:
      +materialized: view

# =====
# Seeds (https://docs.getdbt.com/reference/seed-configs)
# =====

seeds:
  +enabled: true  
  +full_refresh: true

# =========
# Snapshots (https://docs.getdbt.com/reference/snapshot-configs)
# =========

# =======
# Sources (https://docs.getdbt.com/reference/source-configs)
# =======

# =====
# Tests (https://docs.getdbt.com/reference/test-configs)
# =====

# =========
# Variables (https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-variables)
# =========

vars:
  'dbt_date:time_zone': 'America/Los_Angeles'
  # monitoring_configuration: monitoring_configuration
  # dbt_artifacts_database: elastic-bi
  # dbt_artifacts_schema: dbt

# ============
# On Run Start (https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end)
# ============

# ==========
# On Run End (https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end)
# ==========

on-run-end:
  - "{{ elementary.upload_dbt_artifacts(results) }}"

# ========
# Dispatch (https://docs.getdbt.com/reference/project-configs/dispatch-config)
# ========