name: 'dbt'
version: '1.0.0'
config-version: 2
profile: 'dbt'
model-paths: ["models"]
analysis-paths: ["analyses"]
target-path: ["target"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
clean-targets: ["target", "dbt_packages", "logs"]

vars:
  fivetran_log:
    fivetran_log_database: x
    fivetran_log_schema: x
    fivetran_log_using_transformations: false
    fivetran_log_using_triggers: false
    fivetran_log_using_sync_alert_messages: false
  monitoring_configuration: monitoring_configuration
  dbt_artifacts_database: source_system
  dbt_artifacts_schema: monitoring
  'dbt_date:time_zone': 'America/Los_Angeles'

on-run-end:
  - "{{ elementary.upload_dbt_artifacts(results) }}"

models:
  dbt:
    marketing:
      +materialized: view
    revenue:
      +materialized: view

# ======
# Seed Configs
# ======
seeds:
  +enabled: true  
  +database: x
  +schema: x