name: "Build: Daily"

on:
  schedule:
    # https://crontab.guru/
    - cron: "0 10 * * *" # github actions run on UTC

  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  PROJECT: ${{ secrets.PROJECT }}
  DATASET: ${{ secrets.DATASET }}
  KEYFILE: ${{ secrets.KEYFILE }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout Repos
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.API_TOKEN_GITHUB }}

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.12

    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: |       
        dbt deps --profiles-dir . --target prod
        dbt build --select tag:daily --profiles-dir . --target prod

    - name: Notify Slack On Fail
      if: ${{ failure() }}
      uses: craftech-io/slack-action@v1
      with:
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        status: failure
