name: "Integration Testing"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.API_TOKEN_GITHUB }}

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.12

    - name: Install dbt
      run: |
        python -m pip install --upgrade pip && pip install -r requirements.txt

    - name: Test Building Modified Models
      run: |
        echo $KEYFILE > keyfile.json
        dbt deps --profiles-dir .
        dbt build --select state:modified+ --defer --state ./state --full-refresh --profiles-dir . --target ci
      env:
        DATASET: CIRUN_${{ github.run_number }}
        KEYFILE: ${{ secrets.KEYFILE }}

    - name: Build Production Changes & Update Manifest
      if: ${{ success() }}
      run: |
        dbt build --select state:modified+ --state ./state --full-refresh --profiles-dir . --target prod
        dbt docs generate --profiles-dir . --target prod
        cp ./target/index.html ./state/index.html
        cp ./target/manifest.json ./state/manifest.json
        cp ./target/catalog.json ./state/catalog.json

    - name: Add & Commit New Manifest
      if: ${{ success() }}
      uses: EndBug/add-and-commit@v9
      with:
        author_name: dbt CI
        author_email: actions@github.com
        message: 'Update Production Manifest'

    - name: Merge Pull Request On Pass
      if: ${{ success() }}
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.API_TOKEN_GITHUB }}
        number: ${{ github.event.number }}
        method: squash
