name: "Build: Daily"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout Repos
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.API_TOKEN_GITHUB }}

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.12

    - name: Install dbt & Build
      run: |       
        python -m pip install --upgrade pip && pip install -r requirements.txt
        echo $KEYFILE > ./keyfile.json
        dbt deps && dbt compile --profiles-dir . --target prod
      env: 
        KEYFILE: ${{ secrets.KEYFILE }}
